# Generated by Django 4.2.3 on 2024-08-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submitbutton',
            new_name='Email',
        ),
    ]
